auth
manthankumbhar/frontend_open-source-notion pull request #1
Opened 2022-02-23 22:29 UTC by manthankumbhar

2022-02-25 12:05 UTC, kavadithya requested changes
Home.js, Login.js & Signup.js have major comments; 
minor comments in other places

2022-02-25 12:05 UTC, kavadithya commented on package.json
> +    "@testing-library/jest-dom": "^5.16.1",
move testing packages to devDependencies?

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Home/Home.js
> +  const logout = (e) => {
add useCallback

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Home/Home.js
> +  const logout = (e) => {
it's used to cache functions - improves performance

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Home/Home.js
> +import auth from "../../hoc/auth";
don't use relative paths anywhere if possible - set a root path and use absolute paths from there;

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Home/Home.js
> +import auth from "../../hoc/auth";
do this everywhere - not repeating comment in other places.

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +  const [email, setEmail] = useState("");
why empty string? use null instead

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +    axios
don't use promises - use async / await instead

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +  const [open, setOpen] = useState(false);
what is open? from reading the code, I can't understand what this variable is for; rename variable

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +  const [snackbarMessage, setSnackbarMessage] = useState("");
null initialization everywhere - unless some library prohibits it

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +    axios
async / await everywhere

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +        if (res.status === 200) {
what happens if res.status != 200? case not handled afaict

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +        if (res.status === 200) {
what happens if res.status != 200? case not handled afaict

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +  const handleClose = (event, reason) => {
usecallback

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +        {passwordReset ? (
move to different components to make it more readable

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +  return (
entire block is toooo long - always split up to components to improve readability

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +  return (
will review this block after splitting to components

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Signup/Signup.js
> +export default function Signup() {
repeat some comments from Login - about initialization, naming variables etc.

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Signup/Signup.js
> +export default function Signup() {
too much repeated code here

2022-02-25 12:05 UTC, kavadithya commented on src/Components/Signup/Signup.js
> +              onChange={(e) => setPassword(e.target.value)}
don't use functions directly like this; create a separate function for this, use useCallback, and add that function name here

2022-02-25 12:05 UTC, kavadithya commented on src/hoc/PrivateRoute.js
> +        if (res.status === 200) {
error case not handled

2022-02-25 12:05 UTC, kavadithya commented on src/hoc/PrivateRoute.js
> +        if (res.status === 200) {
server error I mean

2022-02-25 12:05 UTC, kavadithya commented on src/hoc/PrivateRoute.js
> +  return isAuth ? (
too many if / else conditions nested using ?:
don't do that; 
use proper if/else conditions and multiple return statements to make it more readable

2022-02-25 12:05 UTC, kavadithya commented on src/hoc/PrivateRoute.js
> +        <p style={{ fontSize: "35px", fontWeight: "900" }}>
css not separate file for this? unlike other files

2022-02-26 20:35 UTC, manthankumbhar commented on src/Components/Login/Login.js
> +  const [email, setEmail] = useState("");
tried but react gives out an error saying the value prop in the input file shouldn't be kept null, go for empty string instead

2022-02-26 21:26 UTC, manthankumbhar commented on src/Components/Login/Login.js
> +  const [snackbarMessage, setSnackbarMessage] = useState("");
every library needs empty string, not accepting null

2022-02-26 21:27 UTC, manthankumbhar commented on src/Components/Login/Login.js
> +        if (res.status === 200) {
I tried adding case check for 400 but in they end up going to catch error, errors are automatically shifted to catch block and cannot be handled in that particular block

2022-03-02 13:05 UTC, kavadithya requested changes

2022-03-02 13:05 UTC, kavadithya commented on src/Components/Home/Home.js
> +import auth from "../../hoc/auth";
https://stackoverflow.com/questions/41993461/import-react-components-with-absolute-path

2022-03-02 13:05 UTC, kavadithya commented on src/Components/Login/Login.js
> +        if (res.status === 200) {
ok

2022-03-03 12:48 UTC, kavadithya approved these changes
minor comment - please fix & squash merge to master

2022-03-03 12:48 UTC, kavadithya commented on src/App.js
>  import "./App.scss";
avoid if possible

2022-03-03 12:48 UTC, kavadithya commented on src/Components/Home/Home.js
> +import "./Home.scss";
fix

2022-04-14 08:33 UTC, closed without merging